# Generated by Django 3.0.14 on 2021-08-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='Add a Description', max_length=400),
        ),
    ]
