# Generated by Django 3.0.14 on 2021-08-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
